# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f68ce761227bcec84b93c8f6ccd7ef07178a436d9b70d98269a3d6a32d77d22a9582bb157ee493b182eba4cf5f950fbcd77d071b838b7a3cf87af36cb84fc1bd

test:
  secret_key_base: 0fe24a9b2f34c45563920273e7e136fb9d91cc196a255bd194caf4c3242dfe53fcae0ec23eac333f5f99f23e989c5bb950abdf26b8c2da8afa68dbbdcc4d97da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
